### ISSUE TITLE
Crash on screen rotate

### ISSUE THREAD

**Issue by sylvia43** [a1studmuffin/Cataclysm-DDA-Android#51] opened 2017-06-03 16:49 UTC
I'm playing the game on Android, and when I go into settings and change the screen orientation setting from "Sensor" to "Landscape," the game changes orientation then promptly shuts down. There's no "this app has stopped working/stopped responding/crashed" message, and the app still shows up on the recents list, but when I reopen it it acts like I'm starting it for the first time and that settings change isn't saved.

I can't connect to adb right now but I could later and try and replicate the issue.

**Comment by a1studmuffin** [comment] 2017-06-10 11:41
Thanks for the report. A few questions:
- Which version of the app?
- Phone model?
- Android version?
- Is Software Rendering enabled in the Graphics settings? 

You may be able to dodge the crash until it's fixed by disabling the software renderer.

**Comment by sylvia43** [comment] 2017-06-10 16:37
Version 0.4.5
OnePlus 2 with Oxygen OS 3.5.8, Android 6.0.1

I tried disabling software rendering and after restarting I ran into the garbled graphics bug, but I managed to change the screen rotation then and it worked. However, when I tried changing back to software rendering, it crashed again.

**Comment by Dyrewulfe** [comment] 2017-06-28 09:42
Orientation is locked to landscape for now. Please let us know if you experience any crash issues when locking the screen or otherwise switching out of the game(My test device that had this problem is working fine with software rendering in the current version.)

**Comment by ghost** [comment] 2017-08-23 02:16
Hi, I'm having the same issue with the game crashing whenever I switch apps.
Version: 0.4.7
Phone model: OnePlus 3
Android: 7.1.1 LineageOS
SW rendering: yes

The problem goes away when SW rendering is disabled.

**Comment by a1studmuffin** [comment] 2017-08-23 08:11
Thanks for the report! This is a known bug, sorry for the inconvenience.

**Comment by ghost** [comment] 2017-08-23 08:17
Thanks for your work on this project! Could you please explain the cause/source of this problem if possible?

Thanks.

**Comment by sylvia43** [comment] 2017-08-23 14:24
It probably has to do with android's lifecycle and/or the opengl/sdl graphics context. Android is tricky to work with for these kinds of things.

**Comment by a1studmuffin** [comment] 2017-08-29 07:57
I believe it's related to some changes we made to work around this issue:
https://bugzilla.libsdl.org/show_bug.cgi?id=3605

**Closed as completed** 2018-10-15 03:56 UTC
