### ISSUE TITLE
Garbled screen textures on certain devices w/Android 6.0.1

### ISSUE THREAD

**Issue by a1studmuffin** [a1studmuffin/Cataclysm-DDA-Android#5] opened 2017-04-13 04:16 UTC
This appears to be an issue with hardware acceleration (specifically the 'opengles2' renderer) on certain Android devices only, running 6.0.1. 

Bug report examples: https://www.reddit.com/r/cataclysmdda/comments/5rjo4i/android_version_beta_test_has_begun/dd82dft/?context=3
https://www.reddit.com/r/cataclysmdda/comments/5rjo4i/android_version_beta_test_has_begun/dd8371c/
https://www.reddit.com/r/cataclysmdda/comments/5rjo4i/android_version_beta_test_has_begun/dd9l70h/

Seen on:
- Blackberry Priv w/ Android 6.0.1
- LG V10 w/ unknown Android version
- Samsung Galaxy S7 w/ Android 6.0.1
- EMUI 4.0 w/Android 6.0.1
- Samsung Galaxy Note 4 w/Android 6.0.1
- Xiaomi Redmi 3s w/Android 6.0.1

Notes:
- Does not show up in x86 emulators.
- If tiles are disabled, the build seems to run fine.
- Appears to be fairly low level, ie. SDL getting confused about texture memory. If you play the game, it's not just character glyphs that get confused. The pixel minimap texture will be drawn using the wrong texture data as well. The actual graphical tiles seem fine though.
- When one user upgraded to Android 7 on the same device, the issue resolved itself.

**Comment by Dyrewulfe** [comment] 2017-04-13 20:27
Could try using SDL_SetHint(SDL_HINT_RENDER_DRIVER, "opengles")? If the problem is specific to gles2, that will try to force gles1. Might be worth a shot.

**Comment by Dyrewulfe** [comment] 2017-04-14 04:04
> The actual graphical tiles seem fine though.

That's good to know, and important. I think I "might" have a solution.

**Comment by a1studmuffin** [comment] 2017-04-14 08:46
FWIW I tried forcing the 'opengles' driver with a hint. It worked and no corruption occurred, however performance seemed much worse on the Note 4 I was testing on.

**Comment by Dyrewulfe** [comment] 2017-04-14 19:24
I suspected it might. I'm not a GL guru, so I really can't be certain, but my gut is saying that those particular devices are having an issue with the constant binding and unbinding of textures in the drawing routines. Essentially, texture for 'x' gets bound, drawing is done, texture is not unbound correctly, next bind fails silently(at least on our end? Do we have any useful logcat about this?), and then it gets locked into drawing that texture repeatedly.

I think in this case, the only fix we could do is to remove the constant texture swapping. Not certain that would fix the problem, though. Either way it'll improve hw rendering performance.

**Comment by a1studmuffin** [comment] 2017-04-16 04:25
Yeah this sounds very possible. There is a good tell in the garbled
screenshots of the welcome screen people have submitted:

https://imgur.com/yRHUyxV,JJz2PMw#yRHUyxV

 The opening text starts with:

`Welcome to the `

but the garbled display shows it as:

`Welcomm tttthhh`

There's a pattern here if you assume it's drawing from left to right. The
first time it draws a character glyph, it draws the correct glyph. But
whenever it tries to draw a character glyph that's already been drawn this
frame, it uses the last-drawn texture instead. (If you follow this pattern
beyond the small text snippit above you'll see it's consistent through the
entire screenshot.)

I've traced through the text & glyph-rendering code on the game-side on a
"broken" device and I am sure everything is working properly with regards
to creating/accessing the font glyphs. The issue appears to be further down
in the SDL library. This would also explain why it's only broken on certain
devices with a certain Android version... there must be some low-level
stuff going on with accessing textures and that specific version of the
Android API. It could actually be an Android 6.x bug that SDL simply
triggers.

**Comment by a1studmuffin** [comment] 2017-04-16 04:28
Yeah this sounds very possible. There is a good tell in the garbled screenshots of the welcome screen people have submitted: https://imgur.com/yRHUyxV,JJz2PMw

 The opening text starts with:

`Welcome to the `

but the garbled display shows it as:

`Welcomm tttthhh`

There's a pattern here if you assume it's drawing from left to right. The first time it draws a character glyph, it draws the correct glyph. But whenever it tries to draw a character glyph that's already been drawn this frame, it uses the last-drawn texture instead. (If you follow this pattern beyond the small text snippit above you'll see it's consistent through the entire screenshot.)

I've traced through the text & glyph-rendering code on the game-side on a "broken" device and I am sure everything is working properly with regards to creating/accessing the font glyphs. The issue appears to be further down in the SDL library. This would also explain why it's only broken on certain devices with a certain Android version... there must be some low-level stuff going on with accessing textures and that specific version of the Android API. It could actually be an Android 6.x bug that SDL simply triggers.

**Comment by Dyrewulfe** [comment] 2017-04-16 05:07
All of those devices either run, or have versions that run, Adreno gpus, from what I can tell. Sounds like a broken gles2 driver that shipped with 6.0.1.

**Comment by Dyrewulfe** [comment] 2017-05-04 00:55
Closing this now that software rendering is stable.I don't believe that there's more we can do for this.

**Closed as completed by Dyrewulfe** 2017-05-04 00:55 UTC
Labels: bug
